/*
 * Copyright 2019 IceRock MAG Inc. Use of this source code is governed by the Apache 2.0 license.
 */

package org.example.app.units

import dev.icerock.moko.resources.desc.StringDesc
import dev.icerock.moko.units.TableUnitItem
import org.example.app.TileNews
import org.example.library.SharedFactory

class NewsListUnitsFactory : SharedFactory.NewsUnitsFactory {
    override fun createNewsTile(
        id: Long,
        title: String,
        description: StringDesc
    ): TableUnitItem {
        // TileNews is generated by units plugin from https://github.com/icerockdev/moko-units
        // generation based on databinding layouts
        return TileNews().apply {
            itemId = id
            this.title = title
            this.description = description
        }
    }
}
